#!/bin/sh

eval $(env | grep "^SYNOPKG_PKGDEST=")
#eval $(env | grep "^config_search=")
eval $(env | grep "^config_scansfolder=")
eval $(env | grep "^config_port=")
eval $(env | grep "^config_gcpconfig=")
#eval $(env | grep "^config_wait=")
eval $(env | grep "^config_beep=")
eval $(env | grep "^config_led=")
eval $(env | grep "^config_notify=")

echo "SCANSFOLDER=$config_scansfolder" > "$SYNOPKG_PKGDEST/config"
echo "PORT=$config_port" >> "$SYNOPKG_PKGDEST/config"

default_gcp_value="{\"local_printing_enable\": true\"cloud_printing_enable\": true\"xmpp_jid\": \"XXX\"\"robot_refresh_token\": \"XXX\"\"user_refresh_token\": \"XXX\"\"proxy_name\":\"XXX\"\"log_level\":\"INFO\"\"log_file_name\": \"/tmp/cloud-print-connector\"}"
if [ "$config_gcpconfig" = "$default_gcp_value" ]; then
	echo "POSTINSTALL: gcp_config was left to defaule, ignoring it." >> "$SYNOPKG_PKGDEST/log"
else
	echo "GCPCONFIG='$config_gcpconfig'" >> "$SYNOPKG_PKGDEST/config"
	echo "GCPCONFIG=$config_gcpconfig" > "$SYNOPKG_PKGDEST/envfile"
fi
if [ $config_beep = "true" ]
then
	echo "BEEP=1" >> "$SYNOPKG_PKGDEST/config"
else
	echo "BEEP=0" >> "$SYNOPKG_PKGDEST/config"
fi
if [ $config_led = "true" ]
then
	echo "LED=1" >> "$SYNOPKG_PKGDEST/config"
else
	echo "LED=0" >> "$SYNOPKG_PKGDEST/config"
fi
if [ -z "$config_notify" ]
then
	echo "NOTIFY=0" >> "$SYNOPKG_PKGDEST/config"
else
	echo "NOTIFY=1" >> "$SYNOPKG_PKGDEST/config"
fi
echo "NOTIFYTARGET=$config_notify" >> "$SYNOPKG_PKGDEST/config"

chmod 700 "$SYNOPKG_PKGDEST/autorun"
chmod 700 "$SYNOPKG_PKGDEST/common"
chmod 600 "$SYNOPKG_PKGDEST/config"
chmod 400 "$SYNOPKG_PKGDEST/rules"
chmod 700 "$SYNOPKG_PKGDEST/udev"
chown -R admin.users "$SYNOPKG_PKGDEST"
echo "`date +%Y-%m-%d` `date +%H:%M:%S`: mfc7320 installed<br/>" >> "${SYNOPKG_PKGDEST}/log"

exit 0
